# List of Services
services:
  spring:
    build: ./spring # Look for Dockerfile in this path
    tty: true
    ports:
      - "8080:8080" # Expose port 8080
    environment:
      # These are used in apllication.property to setup DB connection
      - DB_ADDRESS=jdbc:mysql://mysql:3306
      - DB_DATABASE=template_db
      - DB_USER=root
      - DB_PASSWORD=pwd
    networks:
<<<<<<< HEAD
      - spring-mysql    # Allow the spring app to discover the mysql app
      - spring-react
      - spring-python    # Allow the spring app to talk to the react app
=======
      - spring-mysql # Allow the spring app to discover the mysql app
      - spring-react # Allow the spring app to talk to the react app
>>>>>>> d8be8dc (fixed file structure for backend, created devcontainers for docker, create simplae route in backend, chnaged from maven to gradle for building and updated dockerfile to work with it.)

  mysql:
    build: ./mysql # Look for Dockerfile in this path
    ports:
      - "3306:3306"
    environment:
      # Mysql docker image env vars
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=template_db
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
<<<<<<< HEAD
      - spring-mysql    # Allow the mysql app to talk to the spring app

  python:
    build: ./python

    networks:
      - spring-python
      
=======
      - spring-mysql # Allow the mysql app to talk to the spring app

>>>>>>> d8be8dc (fixed file structure for backend, created devcontainers for docker, create simplae route in backend, chnaged from maven to gradle for building and updated dockerfile to work with it.)
  react:
    build: ./react # Look for Dockerfile in this path
    tty: true
    ports:
      - "3000:3000" # Expose port 3000
    environment:
      # Tell the react app that our spring server is running here
      - BACKEND_PROXY=http://spring:8080
    networks:
<<<<<<< HEAD
      - spring-react    # Allow the react app to discover the spring app
      
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - spring-python
=======
      - spring-react # Allow the react app to discover the spring app
>>>>>>> d8be8dc (fixed file structure for backend, created devcontainers for docker, create simplae route in backend, chnaged from maven to gradle for building and updated dockerfile to work with it.)

volumes:
  mariadb_data:

# List of Networks
networks:
  spring-mysql:
  spring-react:
  spring-python:
