services:
  spring:
    build: ./spring
    ports:
      - "8080:8080"
    environment:
      # These are used in apllication.property to setup DB connection
      - DB_ADDRESS=jdbc:mysql://mysql:3306
      - DB_DATABASE=template_db
      - DB_USER=root
      - DB_PASSWORD=pwd
    networks:
      - spring-mysql
      - spring-react

  mysql:
    build: ./mysql
    environment:
      # Mysql docker image env vars
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=template_db
    networks:
      - spring-mysql
    
  react:
    build: ./react
    ports:
      - "3000:3000"
    environment:
      # Tell the react app that our spring server is running here
      - BACKEND_PROXY=http://spring:8080
    networks:
      - spring-react

  blog:
    build: ./blog
    ports:
      - "4000:4000"
    
networks:
  spring-mysql:
  spring-react:
