services:
  spring:
    build: ./spring
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      # These are used in apllication.property to setup DB connection
      - DB_URL=jdbc:mysql://mysql:3306
      - DB_DATABASE=template_db
      - DB_USER=root
      - DB_PASSWORD=pwd
    networks:
      - spring-mysql
      - spring-react

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      # Mysql docker image env vars
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=template_db
    networks:
      - spring-mysql
    
  react:
    build: ./react
    depends_on:
      - spring
    ports:
      - "3000:3000"
    environment:
      - BACKEND_PROXY=http://spring:8080
    networks:
      - spring-react
    

networks:
  spring-mysql:
  spring-react:
