apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: gitlab-agent-tagent
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5zb2NzLnVvZ3VlbHBoLmNhIjp7InVzZXJuYW1lIjoiYW1lcmNoMDQiLCJwYXNzd29yZCI6ImdscGF0LVh6SFB5RmplekRUbmpidkNoOUN4IiwiYXV0aCI6IllXMWxjbU5vTURRNloyeHdZWFF0V0hwSVVIbEdhbVY2UkZSdWFtSjJRMmc1UTNnPSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: gitlab-agent-a
type: kubernetes.io/dockerconfigjson
