apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  namespace: gitlab-agent-local
spec:
  replica: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: registry.socs.uoguelph.ca/amerch04/springtemplate/blog:v0.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name : regcred
