apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: gitlab-agent-tagent
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: registry.socs.uoguelph.ca/amerch04/springtemplate/mysql:v0.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: pwd
          - name: MYSQL_DATABASE
            value: template_db
        ports:
        - containerPort: 3360
      imagePullSecrets:
      - name : regcred
