apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: gitlab-agent-local
  labels:
    name: ingress
spec:
  rules:
  - host: amerch04.socs.uoguelph.ca
    http:
      paths:
      - path: /console
        pathType: Prefix
        backend:
          service:
            name: react-service
            port: 
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: spring-service
            port: 
              number: 8080
  ingressClassName: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: gitlab-agent-local
spec:
  selector:
    app: spring
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: gitlab-agent-local
spec:
  selector:
    app: react
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: gitlab-agent-local
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5zb2NzLnVvZ3VlbHBoLmNhIjp7InVzZXJuYW1lIjoiYW1lcmNoMDQiLCJwYXNzd29yZCI6ImdscGF0LUhQZHh5SzNmdEFrSm5NY05CUjEtIiwiYXV0aCI6IllXMWxjbU5vTURRNloyeHdZWFF0U0ZCa2VIbExNMlowUVd0S2JrMWpUa0pTTVMwPSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: gitlab-agent-local
type: kubernetes.io/dockerconfigjson
