apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: gitlab-agent-local
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - amerch04.socs.uoguelph.ca
    secretName: template-tls
  rules:
  - host: amerch04.socs.uoguelph.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-service
            port: 
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: spring-service
            port: 
              number: 8080
      - path: /blogs
        pathType: Prefix
        backend:
          service:
            name: blog-service
            port: 
              number: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: gitlab-agent-local
spec:
  selector:
    app: spring
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: gitlab-agent-local
spec:
  selector:
    app: react
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: gitlab-agent-local
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: gitlab-agent-local
spec:
  selector:
    app: blog
  ports:
  - port: 4000
    targetPort: 4000
---
apiVersion: v1
data:
  .dockerconfigjson: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICAicmVnaXN0cnkuc29jcy51b2d1ZWxwaC5jYSI6IHsNCiAgICAgICAgICAgICAgICAgInVzZXJuYW1lIjogImFtZXJjaDA0IiwNCiAgICAgICAgICAgICAgICAgInBhc3N3b3JkIjogImdscGF0LTh3MzdpbmtaTGhhNjNXYWNSR3pYIg0KICAgICAgICAgICB9DQogICB9DQp9
kind: Secret
metadata:
  name: regcred
  namespace: gitlab-agent-local
type: kubernetes.io/dockerconfigjson
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: gitlab-agent-local
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: amerch04@uoguelph.ca
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx