apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: gitlab-agent-local
  labels:
    name: ingress
spec:
  rules:
  - host: template.uoguelph.ca
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: react-service
            port: 
              number: 3000
  - host: api.template.uoguelph.ca
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: spring-service
            port: 
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: gitlab-agent-local
spec:
  selector:
    app: spring
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: gitlab-agent-local
spec:
  selector:
    app: react
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: gitlab-agent-local
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5zb2NzLnVvZ3VlbHBoLmNhIjp7InVzZXJuYW1lIjoiXHUwMDNjYW1lcmNoMDRcdTAwM2UiLCJwYXNzd29yZCI6Ilx1MDAzY2dscGF0LUhQZHh5SzNmdEFrSm5NY05CUjEtXHUwMDNlIiwiYXV0aCI6IlBHRnRaWEpqYURBMFBqbzhaMnh3WVhRdFNGQmtlSGxMTTJaMFFXdEtiazFqVGtKU01TMCsifX19
kind: Secret
metadata:
  name: regcred
  namespace: gitlab-agent-local
type: kubernetes.io/dockerconfigjson
