apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  namespace: gitlab-agent-tagent
  labels:
    app: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: registry.socs.uoguelph.ca/amerch04/springtemplate/react:v0.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
          - name: BACKEND_PROXY
            value: http://spring-service:8080
      imagePullSecrets:
      - name : regcred
