apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: amerch/springtemplate:spring
        env:
          - name: DB_HOST
            value: mysql-service
          - name: DB_DATABASE
            value: template_db
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            value: pwd
